import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:smart_age_calculator_pro/domain/entities/age_result.dart';

class PdfReportService {
  static Future<Uint8List> buildReport({
    required String name,
    required DateTime dob,
    required AgeResult ageResult,
  }) async {
    final doc = pw.Document();
    final now = DateTime.now();

    doc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Center(
                child: pw.Text(
                  'AGE REPORT',
                  style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold),
                ),
              ),
              pw.SizedBox(height: 20),
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text('Name: ${name.isEmpty ? 'N/A' : name}',
                      style: const pw.TextStyle(fontSize: 14)),
                  pw.Text(
                    'Generated: ${now.day}/${now.month}/${now.year}',
                    style: const pw.TextStyle(fontSize: 14),
                  ),
                ],
              ),
              pw.SizedBox(height: 6),
              pw.Text(
                'Date of Birth: ${dob.day}/${dob.month}/${dob.year}',
                style: const pw.TextStyle(fontSize: 14),
              ),
              pw.SizedBox(height: 20),
              pw.Table.fromTextArray(
                headers: const ['Category', 'Value'],
                data: [
                  ['Exact Age', '${ageResult.years} years, ${ageResult.months} months, ${ageResult.days} days'],
                  ['Total Days Lived', ageResult.totalDays.toString()],
                  ['Total Weeks Lived', ageResult.totalWeeks.toString()],
                  ['Total Months Lived', ageResult.totalMonths.toString()],
                  ['Total Hours Lived', ageResult.totalHours.toString()],
                  ['Next Birthday', '${ageResult.nextBirthday.day}/${ageResult.nextBirthday.month}/${ageResult.nextBirthday.year}'],
                  ['Days Until Next Birthday', ageResult.daysUntilBirthday.toString()],
                ],
                headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                cellAlignment: pw.Alignment.centerLeft,
                border: pw.TableBorder.all(color: PdfColors.grey400),
              ),
              pw.SizedBox(height: 24),
              pw.Text(
                'Generated by Smart Age Calculator Pro',
                style: pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
              ),
            ],
          );
        },
      ),
    );

    return doc.save();
  }
}
